import 'package:flutter/material.dart';
import 'package:flutterapp/earnilyapp/generatedtasklistwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/earnilyapp/generatedtasklistwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/earnilyapp/generatedtasklistwidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/earnilyapp/generatedtasklistwidget/generated/GeneratedWidget1.dart';

/* Frame task list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTasklistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 75.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 135.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 94.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedWidget1(),
              )
            ]),
      ),
    ));
  }
}
