import 'package:flutter/material.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget7.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget6.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget8.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/earnilyapp/generatedaddtaskwidget/generated/GeneratedWidget2.dart';

/* Frame add task
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddtaskWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 75.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 40.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 273.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 45.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 316.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 48.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 328.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 48.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 316.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 48.0,
                child: GeneratedWidget6(),
              ),
              Positioned(
                left: 232.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 45.0,
                child: GeneratedWidget7(),
              ),
              Positioned(
                left: 29.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 126.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 135.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 106.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedWidget8(),
              ),
              Positioned(
                left: 57.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 35.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 35.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 35.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 43.0,
                child: GeneratedRectangle7Widget(),
              )
            ]),
      ),
    ));
  }
}
